version: '3.9'

services:
  yii:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - USER_NAME=${USER_NAME:-appuser}
    container_name: yii
    working_dir: /var/www/html/yii
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
    extra_hosts:
        - 'host.docker.internal:host-gateway'      
    ports:
        - '8502:8502'
        - '9003:9003'
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - moneymonkey_network

  npm:
    image: node:18
    container_name: npm
    working_dir: /var/www/html/npm
    ports:
        - '8080:8080'
    volumes:
      - .:/var/www/html
    user: 'node'      
    command: sh -c "npm install && npm start"
    networks:
      - moneymonkey_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./data/db/mysql:/var/lib/mysql
    networks:
      - moneymonkey_network

networks:
  moneymonkey_network:
    name: moneymonkey_network
